import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ['DM Sans', 'system-ui', 'sans-serif'],
        display: ['Inter', 'serif'],
      },
      colors: {
        // ── Stitch Design System tokens ──────────────────────────────
        "brand-primary": "#b22b00",
        "surface": "#fff8f5",
        "surface-container": "#f3ecea",
        "surface-container-low": "#f9f2ef",
        "surface-container-high": "#ede7e4",
        "surface-container-highest": "#e8e1de",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#fff8f5",
        "surface-dim": "#dfd9d6",
        "surface-variant": "#e8e1de",
        "surface-tint": "#b22b00",
        "on-surface": "#1d1b1a",
        "on-surface-variant": "#5b403a",
        "on-background-ds": "#1d1b1a",
        "on-primary": "#ffffff",
        "on-secondary-ds": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-error-ds": "#ffffff",
        "primary-container": "#ff5b2e",
        "on-primary-container": "#581100",
        "primary-fixed": "#ffdbd1",
        "primary-fixed-dim": "#ffb5a1",
        "on-primary-fixed": "#3c0800",
        "on-primary-fixed-variant": "#881f00",
        "inverse-primary": "#ffb5a1",
        "secondary-container-ds": "#e2dfde",
        "on-secondary-container-ds": "#636262",
        "secondary-fixed": "#e5e2e1",
        "secondary-fixed-dim": "#c8c6c5",
        "on-secondary-fixed": "#1c1b1b",
        "on-secondary-fixed-variant": "#474746",
        "tertiary-ds": "#006c49",
        "tertiary-container-ds": "#00a773",
        "on-tertiary-container-ds": "#003320",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",
        "outline-ds": "#8f7068",
        "outline-variant": "#e3beb5",
        "inverse-surface": "#33302e",
        "inverse-on-surface": "#f6efec",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "blush": "#FFE5DC",
        // ─────────────────────────────────────────────────────────────
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      boxShadow: {
        'soft': 'var(--shadow-soft)',
        'card': 'var(--shadow-card)',
        'elevated': 'var(--shadow-elevated)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
